---
AllCops:
  DisabledByDefault: true
  UseCache: true
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
Layout/ClosingHeredocIndentation:
  Enabled: true
Layout/ClosingParenthesisIndentation:
  Enabled: true
Layout/EmptyComment:
  Enabled: true
Layout/EmptyLineAfterMagicComment:
  Enabled: true
Layout/EmptyLineBetweenDefs:
  Enabled: true
Layout/EmptyLines:
  Enabled: true
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
Layout/EmptyLinesAroundArguments:
  Enabled: true
Layout/EmptyLinesAroundBeginBody:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
Layout/EmptyLinesAroundClassBody:
  Enabled: true
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true
Layout/EmptyLinesAroundMethodBody:
  Enabled: true
Layout/EmptyLinesAroundModuleBody:
  Enabled: true
Layout/EndOfLine:
  Enabled: true
Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: key
  EnforcedLastArgumentHashStyle: always_inspect
Layout/IndentationWidth:
  Enabled: true
Layout/LeadingEmptyLines:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space
Layout/SpaceInsideParens:
  Enabled: true
Layout/IndentationStyle:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true
Style/Alias:
  Enabled: true
Style/BlockComments:
  Enabled: true
Style/BlockDelimiters:
  Enabled: true
Style/ClassCheck:
  Enabled: true
Style/CommentAnnotation:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Style/Dir:
  Enabled: true
Style/ExpandPathArguments:
  Enabled: true
Style/For:
  Enabled: true
  EnforcedStyle: each
Style/FormatString:
  Enabled: true
  EnforcedStyle: format
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
Style/MethodCallWithoutArgsParentheses:
  Enabled: true
Style/MethodDefParentheses:
  Enabled: true
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
